config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :wits

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/wit.rb
class Wit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :first_name, :last_name, :age, :location)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@wits = Wit.all # Never do this on large (production) applications
  end
end

app/controllers/wits_controller.rb
class WitsController < ApplicationController
  before_action :set_wit, only: [:show, :edit, :update, :destroy]

  # GET /wits
  # GET /wits.json
  def index
    @wits = Wit.all
  end

  # GET /wits/1
  # GET /wits/1.json
  def show
  end

  # GET /wits/new
  def new
    @wit = Wit.new
  end

  # GET /wits/1/edit
  def edit
  end

  # POST /wits
  # POST /wits.json
  def create
    @wit = Wit.new(wit_params)

    respond_to do |format|
      if @wit.save
        format.html { redirect_to @wit, notice: 'Wit was successfully created.' }
        format.json { render :show, status: :created, location: @wit }
      else
        format.html { render :new }
        format.json { render json: @wit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wits/1
  # PATCH/PUT /wits/1.json
  def update
    respond_to do |format|
      if @wit.update(wit_params)
        format.html { redirect_to @wit, notice: 'Wit was successfully updated.' }
        format.json { render :show, status: :ok, location: @wit }
      else
        format.html { render :edit }
        format.json { render json: @wit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wits/1
  # DELETE /wits/1.json
  def destroy
    @wit.destroy
    respond_to do |format|
      format.html { redirect_to wits_url, notice: 'Wit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wit
      @wit = Wit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wit_params
      params[:wit].permit(:message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wits_helper.rb
module WitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Witter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1><%= link_to 'Witter', root_path %></h1>

<%= link_to "New Wit", new_wit_path %>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.age %></td>
        <td><%= user.location %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h3>Welcome To Witter</h3>
<p>The wittiest place on the web</p>

<ul>
  <% @wits.each do |wit| %>
    <li> 
      <%= link_to wit.message, wit_path(wit) %> | <small> <%= time_ago_in_words(wit.created_at) %> ago </small>
    </li>
  <% end %>
</ul>

app/views/wits/_form.html.erb
<%= form_for(@wit) do |f| %>
  <% if @wit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wit.errors.count, "error") %> prohibited this wit from being saved:</h2>

      <ul>
      <% @wit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= f.label :message, "Message" %>
    <%= f.text_field :message %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wits/edit.html.erb
<h1>Editing Wit</h1>

<%= render 'form' %>

<%= link_to 'Show', @wit %> |
<%= link_to 'Back', wits_path %>

app/views/wits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wits</h1>

<table>
  <thead>
    <tr>
      <th colspan="3">Message</th>
    </tr>
  </thead>

  <tbody>
    <% @wits.each do |wit| %>
      <tr>
        <td><%= wit.message %></td>
      </tr>
      <tr>
        <td><%= link_to 'Show', wit %></td>
        <td><%= link_to 'Edit', edit_wit_path(wit) %></td>
        <td><%= link_to 'Destroy', wit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wit', new_wit_path %>

app/views/wits/new.html.erb
<h1>New Wit</h1>

<%= render 'form' %>

<%= link_to 'Back', wits_path %>

app/views/wits/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= @wit.message %></p>
<small><%= time_ago_in_words(@wit.created_at) %></small>

<div class='actions'>
	<%= link_to 'Edit', edit_wit_path(@wit) %> |
	<%= link_to 'Back', wits_path %>
</div>